### ISSUE TITLE
Buggy 2.0.7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nsalomonis/altanalyze#18]
```
Dear Developers,
There seems to be a problem with the newer versions of AltAnalyze in my case. 
I'm sure if it's working for other people then it's something in that can be 
solved. But here's a short description:
I have a table of Illumina expression values that I can feed successfully into 
version 2.0.3 for example and get an ExpressionOutput folder with my results. 
It doesn't provide me with any annotation data though, but that is secondary.
When I use the same file in 2.0.6 or 2.0.7 it gives me an error that looks like 
this, regardless of the data I pass on to it:

"Beginning to Process the Mm 3'array dataset
Adding additional gene, GO and WikiPathways annotations
* * * * * * * * * * * * * * * * * * * ArrayID annotations imported in 15 seconds
45599 Array IDs with annotations from Illumina annotation files imported.
Processing the expression file: 
R:/Data/Transcriptomics/Illumina/TiKC_den+PC_GA+TA/20120803_ExpressionValues_Raw
_DM.txt
25697 IDs imported...beginning to calculate statistics for all group comparisons
Traceback (most recent call last):
  File "AltAnalyze.pyc", line 4916, in AltAnalyzeSetup
  File "AltAnalyze.pyc", line 4374, in __init__
  File "AltAnalyze.pyc", line 5207, in AltAnalyzeMain
  File "ExpressionBuilder.pyc", line 1360, in remoteExpressionBuilder
  File "ExpressionBuilder.pyc", line 145, in calculate_expression_measures
  File "reorder_arrays.pyc", line 124, in reorder
  File "statistics.pyc", line 492, in log_fold_conversion
OverflowError: math range error


...exiting AltAnalyze due to unexpected error"

Since the issue doesn't change with the type of data set I'm feeding into it, 
I'm finding it hard to figure out what the problem is. I also checked the files 
for NAs or non-numeric entries, but there are none.
Any idea what the problem might be?

Thanks a bunch!

PS: I'm operating on a 64-bit windows 7 system.
```

Original issue reported on code.google.com by `douaa.mu...@gmail.com` on 14 Aug 2012 at 8:59

Attachments:
- [AltAnalyze_report-20120814-092153.log](https://storage.googleapis.com/google-code-attachments/altanalyze/issue-18/comment-0/AltAnalyze_report-20120814-092153.log)

**Comment by nsalomonis** [comment]
Should be resolved in later versions.
