### ISSUE TITLE
Error: No such file or directory: python2.7/site-packages/altanalyze/Config//arrays.txt

### ISSUE THREAD

**Issue by therealgenna** [nsalomonis/altanalyze#48]
I just installed AltAnalyze through `pip` in conda environment (with python 2.7) and following instructions [here](https://altanalyze.readthedocs.io/en/latest/ICGS/) tried to install the organism database with
`altanalyze --species Dr --update Official  --additional all --version EnsMart102`

This threw the following error (I've replaced some paths with /path/to/):

```
Current database version: EnsMart102
AltAnalyze.py --species Dr --update Official --additional all --version EnsMart102
Traceback (most recent call last):
  File "AltAnalyze.py", line 8435, in runCommandLineVersion
    commandLineRun()
  File "AltAnalyze.py", line 7951, in commandLineRun
    array_codes = UI.remoteArrayInfo()
  File "/path/to/lib/python2.7/site-packages/altanalyze/UI.py", line 3679, in remoteArrayInfo
    importArrayInfo()
  File "/path/to/lib/python2.7/site-packages/altanalyze/UI.py", line 3685, in importArrayInfo
    for line in open(fn,'rU').readlines():
IOError: [Errno 2] No such file or directory: '/path/to/lib/python2.7/site-packages/altanalyze/Config//arrays.txt'
```

I don't know what should I do with it. Any help is appreciated.

**Comment by therealgenna** [comment]
Before the above, with `--version EnsMart102`, I tried without the `--version` : `altanalyze_ICGS2]$ altanalyze --species Dr --update Official  --additional all` and got this error:

```
AltAnalyze depedency not met for: wx
...The AltAnalyze Results Viewer requires wx

WARNING!!!! Some dependencies are not currently met.
This may impact AltAnalyze's performance

Running commandline options

Arguments input: ['AltAnalyze.py', '--species', 'Dr', '--update', 'Official', '--additional', 'all'] 

AltAnalyze.py --species Dr --update Official --additional all
Downloading the following file: species_all.txt   Connection opened. Downloading (be patient)
* 

Downloading the following file: source_data.txt   Connection opened. Downloading (be patient)
* 

Downloading the following file: array_versions.txt   Connection opened. Downloading (be patient)
* * 

Finished downloading the latest configuration files.
Species name to update: Danio rerio
Ensembl version current
Traceback (most recent call last):
  File "AltAnalyze.py", line 8435, in runCommandLineVersion
    commandLineRun()
  File "AltAnalyze.py", line 7975, in commandLineRun
    for ad in db_versions_vendors[db_version]:
KeyError: 'current'
```

**Comment by nsalomonis** [comment]
EnsMart102 is not currently provided unless you end up building it on your
end which is possible. Can you run with --version EnsMart72 ? This is an
older version of Ensembl but the default supported version (EnsMart100 is
build an in testing but not yet uploaded).

If required, let me know.

Best,

Nathan

**Comment by therealgenna** [comment]
Now I see that `arrays.txt` sits in a different place, under my home directory `~/altanalyze/Config/`, and this is not where the script is looking for it -  in `/path/to/lib/python2.7/site-packages/altanalyze/Config//arrays.txt` which is under the python installation! Under pythin installation, in the Config dir I have the following files:
`array_versions.txt  report.log  source_data.txt  species_all.txt  version.txt`

**Comment by therealgenna** [comment]
Hi Nathan, thank you for a quick response! No, just tried - it's the same with `--version EnsMart72`. I think it's because different files got into different places, as I posted above. Where should the files like `array.txt` be? It seems strange that the program is looking for it under the python directory tree ...

**Comment by nsalomonis** [comment]
The files should be OK in either place, but it’s possible we are missing
something. As a sanity check, can you download the software from GitHub
from
https://github.com/nsalomonis/altanalyze
 and try again?

**Comment by therealgenna** [comment]
I downloaded, unzipped and ran `python AltAnalyze.py --species Dr --update Official  --additional all --version EnsMart72` which worked. Is `EnsMart72` the latest I can use? I don't want to burden you with creating a newer version if that's the latest - I am not sure I'll need it. I just want to run ICGS2 on scRNAseq to do clustering.

So would you recommend me to just stick with the downloaded version and ignore the one with `pip install altanalyze`?

**Comment by nsalomonis** [comment]
It shouldn’t honestly matter too much (better to have the latest GitHub
version honestly), since it will primarily impact default pathway analyses.

Are you combining multiple h5, mtx or text files? If so, there is a simple
option to do this by adding all of the input files to one folder and
setting that as the target path for ChromiumSparseMatrix

Having R and Biobase and hopach in R will improve the clustering.

Best,
Nathan

**Comment by therealgenna** [comment]
Great, thank you so much! I guess I'll have to extract count matrices and make text files from Seurat objects which were made/merged from multiple 10X run outputs.

**Comment by therealgenna** [comment]
FYI, I noticed that with `pip install` I get `Config.zip` and `AltDatabase.zip` in the `/path/topython2.7/site-packages/altanalyze` but there are no unzipped versions. When I try to install the database as above, the `~/altanalyze` is created in my home directory, under which I also get `~/altanalyze/Config` and `~/altanalyze/AltDatabase`, but then I get the reported error. 

Moving `Config` and `AltDatabase` from `~/altanalyze` to `/path/topython2.7/site-packages/altanalyze` works (and I guess unzipping the zip files would work as well).

**Comment by nsalomonis** [comment]
That is fine or you can add all Cell Ranger sparse matrix outputs to one folder with the appropriate sample names added (e.g., cancer_rep1.h5). ICGS will merge all them appropriately.

If you use a counts tab-delimited text file from Seurat as input, include the option:

--dataFormat counts

If more than 20k cells I suggest:

--downsample 5000 

If the data is already scaled and log2, you can exclude the counts command. When the data is in sparse matrix format it knows to consider it counts.

Best,
Nathan

**Comment by nsalomonis** [comment]
I would still recommend using the GitHub version which addresses a few bugs present in the last pypi release. Much more stable.

The zip files you mentioned are correct. The site-packages path can’t be modified so those folders are extracted to your root user directory and should be looked at by the program first when running which is the expected behavior for the PyPi. Not sure what the issue is yet.

Best,
Nathan

**Comment by therealgenna** [comment]
Awesome, I will follow your recommendations. In the end, after testing it on smaller sets, I might run it on ~400k cells. Will it work? What number should I use for downsampling?

Another question - I've emailed you a day or two ago asking about Louvain resolution in your ICGS2 paper. I wonder if you had a chance to see my email.

Thanks again!

**Comment by nsalomonis** [comment]
Sorry for missing this before. Does the below help (ICGS_NMF.py script):

    from annoy import AnnoyIndex
    t=AnnoyIndex(nm,metric="euclidean")
    for i in range(nn):
        try:  t.add_item(i,X[i])
        except Exception: print i
    t.build(100)
    diclst={}
    for i in range(nn):
        ind=t.get_nns_by_item(i,10)
        diclst[i]=ind
    G=nx.from_dict_of_lists(diclst)
    dendrogram= community.generate_dendrogram(G)
    level=0
    pr= community.partition_at_level(dendrogram,level)
