### ISSUE TITLE
Error running alatanalyze after pip install -- FileNotFoundError: [Errno 2] No such file or directory: 'altanalyze'

### ISSUE THREAD

**Issue by c2b2pss** [nsalomonis/altanalyze#51]
Hi,
I installed altanalyze using the simple command 

`pip install altanalyze`

However, invoking "altanalyze" gives an error that seems to be a pythoncode error.

```
Traceback (most recent call last):
  File "/home/user/.local/bin/altanalyze", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/altanalyze/__init__.py", line 29, in main
    os.chdir("altanalyze")
FileNotFoundError: [Errno 2] No such file or directory: 'altanalyze'
```
Aparently the script does not poerly call and chage the directory.

Any help is appreciated!

Thanks

**Comment by nsalomonis** [comment]
The current version of AltAnalyze is not compatible with Python 3. Please install the latest GitHub (after PyPi to get the dependencies) with Python 2.7. The Python 3 compatible version for splicing analyses should be completed in late 2022. What are you trying to accomplish? 

Best,
Nathan

**Comment by c2b2pss** [comment]
I am just trying to find a GUI way to analyse a RNASeq expression matrix.  Simple stuff, but a GUI is what Im trying.

USing anaconda and a python2 environment I get the following error:

```
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/premsubramaniam/anaconda3/envs/py2/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4MrhFR/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4MrhFR/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0T9ZkF
       cwd: /tmp/pip-install-4MrhFR/llvmlite/
  Complete output (7 lines):
  running bdist_wheel
  /home/premsubramaniam/anaconda3/envs/py2/bin/python2.7 /tmp/pip-install-4MrhFR/llvmlite/ffi/build.py
    File "/tmp/pip-install-4MrhFR/llvmlite/ffi/build.py", line 122
      raise ValueError(msg.format(_ver_check_skip)) from e
                                                       ^
  SyntaxError: invalid syntax
  error: command '/home/premsubramaniam/anaconda3/envs/py2/bin/python2.7' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
ERROR: pynndescent 0.5.6 has requirement numba>=0.51.2, but you'll have numba 0.44.0 which is incompatible.
ERROR: umap-learn 0.5.2 has requirement numba>=0.49, but you'll have numba 0.44.0 which is incompatible.
ERROR: umap-learn 0.5.2 has requirement numpy>=1.17, but you'll have numpy 1.16.6 which is incompatible.
ERROR: umap-learn 0.5.2 has requirement scikit-learn>=0.22, but you'll have scikit-learn 0.20.4 which is incompatible.
Installing collected packages: llvmlite, enum34, numba, pynndescent, typing, scandir, pathlib2, contextlib2, zipp, importlib-resources, tqdm, umap-learn, altanalyze
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /home/premsubramaniam/anaconda3/envs/py2/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4MrhFR/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4MrhFR/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vmduII/install-record.txt --single-version-externally-managed --compile --install-headers /home/premsubramaniam/anaconda3/envs/py2/include/python2.7/llvmlite
         cwd: /tmp/pip-install-4MrhFR/llvmlite/
    Complete output (10 lines):
    running install
    running build
    got version from file /tmp/pip-install-4MrhFR/llvmlite/llvmlite/_version.py {'version': '0.32.1', 'full': 'aa11b129c0b55973067422397821ae6d44fa5e70'}
    running build_ext
    /home/premsubramaniam/anaconda3/envs/py2/bin/python2.7 /tmp/pip-install-4MrhFR/llvmlite/ffi/build.py
      File "/tmp/pip-install-4MrhFR/llvmlite/ffi/build.py", line 122
        raise ValueError(msg.format(_ver_check_skip)) from e
                                                         ^
    SyntaxError: invalid syntax
    error: command '/home/premsubramaniam/anaconda3/envs/py2/bin/python2.7' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/premsubramaniam/anaconda3/envs/py2/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4MrhFR/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4MrhFR/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-vmduII/install-record.txt --single-version-externally-managed --compile --install-headers /home/premsubramaniam/anaconda3/envs/py2/include/python2.7/llvmlite Check the logs for full command output.
(py2) premsubramaniam@pop-os:~$ 
```

**Comment by nsalomonis** [comment]
Thanks for working on the Python 2 solution. We have not worked much with conda environments (although some prior developers typically installed in this environment), but the issue here seems to be with mismatched library versions.

The analyses you describe sound reasonable for the precompiled OS-specific binaries on the AltAnalyze.org website, which don’t require any library or python installations. Have you tried that? Which OS? If still an issue, let us know.

Best,
Nathan

**Comment by nsalomonis** [comment]
Please note, for conda, you may already be good with the installed dependencies for the analyses you want to run. From the GitHub code, running: python AltAnalyze.py from the program directory by command prompt, should prompt the GUI and database installation.

Best,
Nathan
