### ISSUE TITLE
Error running RNASeq analysis with fastq files as input and assigned to groups

### ISSUE THREAD

**Issue by jaydoc** [nsalomonis/altanalyze#52]
When running AltAnalyze to process fastq files using Kallisto-splice if I assign groups to the files then AltAnalyze fails with the following error

> Traceback (most recent call last):
  File "AltAnalyze.py", line 8831, in <module>
    AltAnalyzeSetup(skip_intro)
  File "AltAnalyze.py", line 5185, in AltAnalyzeSetup
    apt_location = fl.APTLocation()
  File "/home/jaydoc/altanalyze-master/UI.py", line 4566, in APTLocation
    def APTLocation(self): return self._apt_location
AttributeError: ExpressionFileLocationData instance has no attribute '_apt_location'

While this happens immediately after the groups are assigned in Ubuntu Linux (source code run with `python2 AltAnalyze.py` the same error happens with the Windows binary version as well, except that it fails after the comparisons are specified. 

I am trying to process 25 samples with paired reads divided into 8 groups (for a total of 28 comparisons) if that helps. 

If I do not assign the groups myself and just check the ICGS option then the program runs kallisto and outputs what I assume are (pseudo)bam files. 

Any help is much appreciated.

**Comment by nsalomonis** [comment]
Greetings,

Could you send the full log file, saved to your output directory by AltAnalyze.

As a test, can you try running from the command line as something like:

python AltAnalyze.py --runICGS yes --platform "RNASeq" --species Mm 
  --column_method hopach --rho 0.4
  --SamplesDiffering 4 --excludeCellCycle conservative --output "C:/FASTQ_Files/" 
  --expname "Mm_HSCs" --fastq_dir "C:/FASTQ_Files/" --runKallisto yes

It is possible it is Unix compilation issue for Kallisto splice and this or the log file should reveal.

Best,
Nathan

**Comment by Junaid13913** [comment]
having same issue below 
-Beginning AltAnalyze Analysis... Format: scaled
AltAnalyze version 2.1.4.4 - Expression Analysis Parameters Being Used...
	database: EnsMart72
	species: Hs
	method: RNASeq
	manufacturer: RNASeq
	probability_statistic: moderated t-test
	constitutive_source: Ensembl
	dabg_p: 1.0
	junction expression threshold: 5.0
	exon_exp_threshold: 5.0
	gene_exp_threshold: 200.0
	exon_rpkm_threshold: 0.5
	gene_rpkm_threshold: 1.0
	exclude low expressing exons for RPKM: no
	avg_all_for_ss: yes
	expression_data_format: scaled
	include_raw_data: no
	run_from_scratch: Process RNA-seq reads
	perform_alt_analysis: yes
	calculate_gene_expression_using: core
Alternative Exon Analysis Parameters Being Used...
	analysis_method: MultiPath-PSI
	p_threshold: 0.05
	filter_data_types: all
	alt_exon_fold_variable: 0.1
	gene_expression_cutoff: 10.0
	remove_intronic_junctions: no
	avg_all_for_ss: yes
	permute_p_threshold: 0.05
	perform_permutation_analysis: no
	export_NI_values: yes
	run_MiDAS: no
	use_direct_domain_alignments_only: inferred comparison
	microRNA_prediction_method: any
	analyze_all_conditions: pairwise
	filter_for_AS: no
	run_GOElite: run-immediately
Using AltDatabase/kallisto/0.43.1/PC/bin/kallisto.exe
Building kallisto index file...
Running kallisto on: GS100DA2 ... kallisto failed due to an unknown error (report to altanalyze.org help).
Trying without BAM file creation.
Re-Building kallisto index file...
kallisto failed due to an unknown error (report to altanalyze.org help).
Traceback (most recent call last):
  File "RNASeq.pyc", line 5286, in runKallisto
  File "RNASeq.pyc", line 5412, in importTPMs
IOError: [Errno 2] No such file or directory: u'E:/project_4///ExpressionInput/kallisto/GS100DA2/abundance.tsv'
